### PR TITLE
Change the folder structure

### LINKED ISSUE #6: Create proper folder structure
A proper and optimised folder structure needs to be created. I was thinking of a server-client classic folder structure, but it is open for discussion. 
Please discuss in this comment thread what you think might be the best option.

### PR DESCRIPTION
**Pull request by sanchibansal340**
Changed the folder structure from public to client and server.

fixes #6 

- Client includes assets and html folder.
- html folder contains the HTML files. The paths in HTML files have been modified accordingly.
- assets contains the js, css, fonts, images folder.

- Server includes all the PHP files 

- public folder has not been deleted.

### CODE REVIEW

**Comment by Harshita248** [comment]
Hey @sanchibansal340   the changes are made in the new sample file which was included by me right? Just wanted to confirm

**Comment by sanchibansal340** [comment]
Uhm I am not sure about the sample file. I made 2 folders client and server as discussed with Shaurya 😅

**Comment by Harshita248** [comment]
So you haven't pulled the changes before doing the pr?

**Comment by sanchibansal340** [comment]
I did but I couldn't find any file named sample.

**Comment by sanchibansal340** [comment]
By sample, do you mean the PHP files?

**Comment by Harshita248** [comment]
@sanchibansal340  I meant the template files in the public folder

**Comment by sanchibansal340** [comment]
Oh @Harshita248 I moved all the folder and files from public to client folder. I added the HTML files to client>html folder and js, images, css, fonts to client>assets folder

**Comment by Harshita248** [comment]
Okay cool

**Pull request merged**
