### PR TITLE
Removed the header section and cart icon from all pages

### PR DESCRIPTION
**Pull request by m-code12**
Removed the shopping cart icon on navbar and remove the header top on all pages which shows the social media icons and other details.

Issue addressed: #73

### CODE REVIEW

**Comment by chehak123** [comment]
kindly add screenshots

**Comment by Harshita248** [comment]
Remove conflicts please @m-code12

**Comment by m-code12** [comment]
Screenshot (14)

Screenshot (15)

Screenshot (17)

Screenshot (16)

**Comment by m-code12** [comment]
Done @chehak123 @Harshita248

**Comment by Harshita248** [comment]
Cool

**Pull request merged**
